In [1]:
import pandas as pd

In [2]:
population=pd.read_csv("/Users/halukamaier-borst/Desktop/DW_DevelopmentalAid/DW_Code/Raw_Data/POP_RAW.csv", encoding='latin1')
population.head()

,Index,Variant,"Region, subregion, country or area *",Notes,Country code,1950,1951,1952,1953,1954,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,1,Estimates,WORLD,NaN,900,2 536 275,2 583 817,2 630 584,2 677 230,2 724 302,...,6 623 848,6 706 419,6 789 771,6 873 741,6 958 169,7 043 009,7 128 177,7 213 426,7 298 453,7 383 009
1,2,Estimates,More developed regions,a,901,814 865,824 213,834 074,844 264,854 632,...,1 215 325,1 220 392,1 225 552,1 230 534,1 235 143,1 239 298,1 243 055,1 246 520,1 249 864,1 253 207
2,3,Estimates,Less developed regions,b,902,1 721 410,1 759 604,1 796 510,1 832 967,1 869 671,...,5 408 523,5 486 027,5 564 219,5 643 207,5 723 027,5 803 711,5 885 122,5 966 906,6 048 590,6 129 802
3,4,Estimates,Least developed countries,c,941,195 259,199 052,202 905,206 885,211 045,...,772 489,790 978,809 731,828 953,848 792,869 298,890 423,912 094,934 192,956 631
4,5,Estimates,"Less developed regions, excluding least develo...",d,934,1 526 151,1 560 552,1 593 605,1 626 082,1 658 626,...,4 636 034,4 695 048,4 754 488,4 814 254,4 874 235,4 934 413,4 994 699,5 054 812,5 114 397,5 173 171

In [3]:
population=population.set_index('Region, subregion, country or area *')
population.head()

,Index,Variant,Notes,Country code,1950,1951,1952,1953,1954,1955,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
"Region, subregion, country or area *",,,,,,,,,,,,,,,,,,,,,
WORLD,1,Estimates,NaN,900,2 536 275,2 583 817,2 630 584,2 677 230,2 724 302,2 772 243,...,6 623 848,6 706 419,6 789 771,6 873 741,6 958 169,7 043 009,7 128 177,7 213 426,7 298 453,7 383 009
More developed regions,2,Estimates,a,901,814 865,824 213,834 074,844 264,854 632,865 069,...,1 215 325,1 220 392,1 225 552,1 230 534,1 235 143,1 239 298,1 243 055,1 246 520,1 249 864,1 253 207
Less developed regions,3,Estimates,b,902,1 721 410,1 759 604,1 796 510,1 832 967,1 869 671,1 907 173,...,5 408 523,5 486 027,5 564 219,5 643 207,5 723 027,5 803 711,5 885 122,5 966 906,6 048 590,6 129 802
Least developed countries,4,Estimates,c,941,195 259,199 052,202 905,206 885,211 045,215 421,...,772 489,790 978,809 731,828 953,848 792,869 298,890 423,912 094,934 192,956 631
"Less developed regions, excluding least developed countries",5,Estimates,d,934,1 526 151,1 560 552,1 593 605,1 626 082,1 658 626,1 691 752,...,4 636 034,4 695 048,4 754 488,4 814 254,4 874 235,4 934 413,4 994 699,5 054 812,5 114 397,5 173 171

In [4]:
country='Zambia'
year='2007'
print(int(population.loc[country][year].replace(" ", ""))*1000)

12726000

In [5]:
#loading in the data for data for ODA and OOF of the last 20 years
rawfile=pd.read_csv("/Users/halukamaier-borst/Desktop/DW_DevelopmentalAid/DW_Code/Raw_Data/Money_RAW_20yrs.csv")

In [6]:
rawfile.head()

,RECIPIENT,Recipient,DONOR,Donor,AIDTYPE,Aid type,PART,Part,TIME,Year,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,10100,"Developing Countries, Total",20005,"All Donors, Total",966,"Total Official, Gross",1,1 : Part I - Developing Countries,1997,1997,USD,US Dollar,6,Millions,NaN,NaN,122240.50,NaN,NaN
1,10100,"Developing Countries, Total",20005,"All Donors, Total",966,"Total Official, Gross",1,1 : Part I - Developing Countries,1998,1998,USD,US Dollar,6,Millions,NaN,NaN,129361.74,NaN,NaN
2,10100,"Developing Countries, Total",20005,"All Donors, Total",966,"Total Official, Gross",1,1 : Part I - Developing Countries,1999,1999,USD,US Dollar,6,Millions,NaN,NaN,138217.50,NaN,NaN
3,10100,"Developing Countries, Total",20005,"All Donors, Total",966,"Total Official, Gross",1,1 : Part I - Developing Countries,2000,2000,USD,US Dollar,6,Millions,NaN,NaN,111921.81,NaN,NaN
4,10100,"Developing Countries, Total",20005,"All Donors, Total",966,"Total Official, Gross",1,1 : Part I - Developing Countries,2001,2001,USD,US Dollar,6,Millions,NaN,NaN,109550.13,NaN,NaN

In [7]:
#sort the data first by recipient and then by donor and define it as the testdata
rawfile=rawfile.sort_values(by=["Recipient","Donor","Year"])
testdata=rawfile
#testdata=testdata.head(10000)

In [8]:
#create and empty dataframe for storing the results
emptyframe = pd.DataFrame(columns=['Recipient','Average Sum of Money'])
#set the value for the previous cell to zero as well as the year and the sum across 20 years
previouscell="0"
year=0
sum20=0
#iterate through the dataframe row by row
for index, row in testdata.iterrows():
    #if the donor is "all donors" and if the aid type is the total official
    if row["Donor"]=="All Donors, Total" and row["Aid type"]=="Total Official, Gross":
        #then set the recipient variable to recipient of the row
        recipient=row["Recipient"]
        annus=str(row["Year"])
        #this if statement is put in place to save the averages whenever the recipient changes
        #from one row to another
        #if the previouscell has not the start value of zero but is also not the current recipient
        #we have such a break
        if previouscell != "0" and previouscell!=recipient:
            #if the number of years is zero, then set the average to zero
            if year==0:
                average=0
                print(previouscell,":",sum20)
            #otherwise calculate the average by dividing the sum over the years through the year
            else:
                average=sum20/year
            #and append the name of the recipient and the average to the dataframe
            df2 = pd.DataFrame([[previouscell, average]], columns=["Recipient","Average Sum of Money"])
            emptyframe=emptyframe.append(df2,ignore_index=True)
            print(previouscell,":",sum20)
            
            try:
                #reset the sum over the years
                sum20=0
                #and add the first value to it that is weighted by population
                cashpercap=row["Value"]*1000000/(int(population.loc[recipient][annus].replace(" ", ""))*1000)
                sum20+=cashpercap
                #set the years count to zero
                year=0
                #and add one to the year count
                year+=1
                #change the previouscell to the recipient
                previouscell=recipient
            except KeyError:
                previouscell=recipient
                pass

            
        #if it is still the same recipient,...
        else:
            print(recipient, annus)
            try:
                #we add the current row value that is weighted by population
                cashpercap=row["Value"]*1000000/(int(population.loc[recipient][annus].replace(" ", ""))*1000)
                sum20+=cashpercap
                #add one year to our year count
                year+=1
                #and change the previouscell name to the current one
                previouscell=recipient
            except KeyError:
                previouscell=recipient
                pass

ACP Countries, Total 1997
ACP Countries, Total 1998
ACP Countries, Total 1999
ACP Countries, Total 2000
ACP Countries, Total 2001
ACP Countries, Total 2002
ACP Countries, Total 2003
ACP Countries, Total 2004
ACP Countries, Total 2005
ACP Countries, Total 2006
ACP Countries, Total 2007
ACP Countries, Total 2008
ACP Countries, Total 2009
ACP Countries, Total 2010
ACP Countries, Total 2011
ACP Countries, Total 2012
ACP Countries, Total 2013
ACP Countries, Total 2014
ACP Countries, Total 2015
ACP Countries, Total : 0
ACP Countries, Total : 0
Afghanistan 1998
Afghanistan 1999
Afghanistan 2000
Afghanistan 2001
Afghanistan 2002
Afghanistan 2003
Afghanistan 2004
Afghanistan 2005
Afghanistan 2006
Afghanistan 2007
Afghanistan 2008
Afghanistan 2009
Afghanistan 2010
Afghanistan 2011
Afghanistan 2012
Afghanistan 2013
Afghanistan 2014
Afghanistan 2015
Afghanistan : 2249.47083005573
Africa, Total 1998
Africa, Total 1999
Africa, Total 2000
Africa, Total 2001
Africa, Total 2002
Africa, Total 2003
Africa, Total 2004
Africa, Total 2005
Africa, Total 2006
Africa, Total 2007
Africa, Total 2008
Africa, Total 2009
Africa, Total 2010
Africa, Total 2011
Africa, Total 2012
Africa, Total 2013
Africa, Total 2014
Africa, Total 2015
Africa, Total : 0
Africa, regional 1998
Africa, regional 1999
Africa, regional 2000
Africa, regional 2001
Africa, regional 2002
Africa, regional 2003
Africa, regional 2004
Africa, regional 2005
Africa, regional 2006
Africa, regional 2007
Africa, regional 2008
Africa, regional 2009
Africa, regional 2010
Africa, regional 2011
Africa, regional 2012
Africa, regional 2013
Africa, regional 2014
Africa, regional 2015
Africa, regional : 0
Albania 1998
Albania 1999
Albania 2000
Albania 2001
Albania 2002
Albania 2003
Albania 2004
Albania 2005
Albania 2006
Albania 2007
Albania 2008
Albania 2009
Albania 2010
Albania 2011
Albania 2012
Albania 2013
Albania 2014
Albania 2015
Albania : 3106.6902585815574
Algeria 1998
Algeria 1999
Algeria 2000
Algeria 2001
Algeria 2002
Algeria 2003
Algeria 2004
Algeria 2005
Algeria 2006
Algeria 2007
Algeria 2008
Algeria 2009
Algeria 2010
Algeria 2011
Algeria 2012
Algeria 2013
Algeria 2014
Algeria 2015
Algeria : 436.97534977101253
America, Total 1998
America, Total 1999
America, Total 2000
America, Total 2001
America, Total 2002
America, Total 2003
America, Total 2004
America, Total 2005
America, Total 2006
America, Total 2007
America, Total 2008
America, Total 2009
America, Total 2010
America, Total 2011
America, Total 2012
America, Total 2013
America, Total 2014
America, Total 2015
America, Total : 0
America, regional 1998
America, regional 1999
America, regional 2000
America, regional 2001
America, regional 2002
America, regional 2003
America, regional 2004
America, regional 2005
America, regional 2006
America, regional 2007
America, regional 2008
America, regional 2009
America, regional 2010
America, regional 2011
America, regional 2012
America, regional 2013
America, regional 2014
America, regional 2015
America, regional : 0
Angola 1998
Angola 1999
Angola 2000
Angola 2001
Angola 2002
Angola 2003
Angola 2004
Angola 2005
Angola 2006
Angola 2007
Angola 2008
Angola 2009
Angola 2010
Angola 2011
Angola 2012
Angola 2013
Angola 2014
Angola 2015
Angola : 676.4020197181068
Anguilla 1998
Anguilla 1999
Anguilla 2000
Anguilla 2001
Anguilla 2002
Anguilla 2003
Anguilla 2004
Anguilla 2005
Anguilla 2006
Anguilla 2007
Anguilla 2008
Anguilla 2009
Anguilla 2010
Anguilla 2011
Anguilla 2012
Anguilla 2013
Anguilla : 11562.733766233769
Antigua and Barbuda 1998
Antigua and Barbuda 1999
Antigua and Barbuda 2000
Antigua and Barbuda 2001
Antigua and Barbuda 2002
Antigua and Barbuda 2003
Antigua and Barbuda 2004
Antigua and Barbuda 2005
Antigua and Barbuda 2006
Antigua and Barbuda 2007
Antigua and Barbuda 2008
Antigua and Barbuda 2009
Antigua and Barbuda 2010
Antigua and Barbuda 2011
Antigua and Barbuda 2012
Antigua and Barbuda 2013
Antigua and Barbuda 2014
Antigua and Barbuda 2015
Antigua and Barbuda : 2428.515000967651
Argentina 1998
Argentina 1999
Argentina 2000
Argentina 2001
Argentina 2002
Argentina 2003
Argentina 2004
Argentina 2005
Argentina 2006
Argentina 2007
Argentina 2008
Argentina 2009
Argentina 2010
Argentina 2011
Argentina 2012
Argentina 2013
Argentina 2014
Argentina 2015
Argentina : 1350.4666868206036
Armenia 1998
Armenia 1999
Armenia 2000
Armenia 2001
Armenia 2002
Armenia 2003
Armenia 2004
Armenia 2005
Armenia 2006
Armenia 2007
Armenia 2008
Armenia 2009
Armenia 2010
Armenia 2011
Armenia 2012
Armenia 2013
Armenia 2014
Armenia 2015
Armenia : 2694.8704860572952
Aruba 1998
Aruba 1999
Aruba : 615.3422370110384
Asia, Total 1998
Asia, Total 1999
Asia, Total 2000
Asia, Total 2001
Asia, Total 2002
Asia, Total 2003
Asia, Total 2004
Asia, Total 2005
Asia, Total 2006
Asia, Total 2007
Asia, Total 2008
Asia, Total 2009
Asia, Total 2010
Asia, Total 2011
Asia, Total 2012
Asia, Total 2013
Asia, Total 2014
Asia, Total 2015
Asia, Total : 0
Asia, regional 1998
Asia, regional 1999
Asia, regional 2000
Asia, regional 2001
Asia, regional 2002
Asia, regional 2003
Asia, regional 2004
Asia, regional 2005
Asia, regional 2006
Asia, regional 2007
Asia, regional 2008
Asia, regional 2009
Asia, regional 2010
Asia, regional 2011
Asia, regional 2012
Asia, regional 2013
Asia, regional 2014
Asia, regional 2015
Asia, regional : 0
Azerbaijan 1998
Azerbaijan 1999
Azerbaijan 2000
Azerbaijan 2001
Azerbaijan 2002
Azerbaijan 2003
Azerbaijan 2004
Azerbaijan 2005
Azerbaijan 2006
Azerbaijan 2007
Azerbaijan 2008
Azerbaijan 2009
Azerbaijan 2010
Azerbaijan 2011
Azerbaijan 2012
Azerbaijan 2013
Azerbaijan 2014
Azerbaijan 2015
Azerbaijan : 1646.8995088012443
Bahrain 1998
Bahrain 1999
Bahrain 2000
Bahrain 2001
Bahrain 2002
Bahrain 2003
Bahrain 2004
Bahrain : 2566.1017582918003
Bangladesh 1998
Bangladesh 1999
Bangladesh 2000
Bangladesh 2001
Bangladesh 2002
Bangladesh 2003
Bangladesh 2004
Bangladesh 2005
Bangladesh 2006
Bangladesh 2007
Bangladesh 2008
Bangladesh 2009
Bangladesh 2010
Bangladesh 2011
Bangladesh 2012
Bangladesh 2013
Bangladesh 2014
Bangladesh 2015
Bangladesh : 319.5243280476167
Barbados 1998
Barbados 1999
Barbados 2000
Barbados 2001
Barbados 2002
Barbados 2003
Barbados 2004
Barbados 2005
Barbados 2006
Barbados 2007
Barbados 2008
Barbados 2009
Barbados 2010
Barbados : 3019.3190002497663
Belarus 2006
Belarus 2007
Belarus 2008
Belarus 2009
Belarus 2010
Belarus 2011
Belarus 2012
Belarus 2013
Belarus 2014
Belarus 2015
Belarus : 808.1510000132887
Belize 1998
Belize 1999
Belize 2000
Belize 2001
Belize 2002
Belize 2003
Belize 2004
Belize 2005
Belize 2006
Belize 2007
Belize 2008
Belize 2009
Belize 2010
Belize 2011
Belize 2012
Belize 2013
Belize 2014
Belize 2015
Belize : 3821.6229751499545
Benin 1998
Benin 1999
Benin 2000
Benin 2001
Benin 2002
Benin 2003
Benin 2004
Benin 2005
Benin 2006
Benin 2007
Benin 2008
Benin 2009
Benin 2010
Benin 2011
Benin 2012
Benin 2013
Benin 2014
Benin 2015
Benin : 1194.1985498700876
Bhutan 1998
Bhutan 1999
Bhutan 2000
Bhutan 2001
Bhutan 2002
Bhutan 2003
Bhutan 2004
Bhutan 2005
Bhutan 2006
Bhutan 2007
Bhutan 2008
Bhutan 2009
Bhutan 2010
Bhutan 2011
Bhutan 2012
Bhutan 2013
Bhutan 2014
Bhutan 2015
Bhutan : 3047.980810252865
Bolivia 1998
Bolivia 1999
Bolivia 2000
Bolivia 2001
Bolivia 2002
Bolivia 2003
Bolivia 2004
Bolivia 2005
Bolivia 2006
Bolivia 2007
Bolivia 2008
Bolivia 2009
Bolivia 2010
Bolivia 2011
Bolivia 2012
Bolivia 2013
Bolivia 2014
Bolivia 2015
Bolivia : 0
Bosnia and Herzegovina 1998
Bosnia and Herzegovina 1999
Bosnia and Herzegovina 2000
Bosnia and Herzegovina 2001
Bosnia and Herzegovina 2002
Bosnia and Herzegovina 2003
Bosnia and Herzegovina 2004
Bosnia and Herzegovina 2005
Bosnia and Herzegovina 2006
Bosnia and Herzegovina 2007
Bosnia and Herzegovina 2008
Bosnia and Herzegovina 2009
Bosnia and Herzegovina 2010
Bosnia and Herzegovina 2011
Bosnia and Herzegovina 2012
Bosnia and Herzegovina 2013
Bosnia and Herzegovina 2014
Bosnia and Herzegovina 2015
Bosnia and Herzegovina : 4565.764341369346
Botswana 1998
Botswana 1999
Botswana 2000
Botswana 2001
Botswana 2002
Botswana 2003
Botswana 2004
Botswana 2005
Botswana 2006
Botswana 2007
Botswana 2008
Botswana 2009
Botswana 2010
Botswana 2011
Botswana 2012
Botswana 2013
Botswana 2014
Botswana 2015
Botswana : 2368.5683496462193
Brazil 1998
Brazil 1999
Brazil 2000
Brazil 2001
Brazil 2002
Brazil 2003
Brazil 2004
Brazil 2005
Brazil 2006
Brazil 2007
Brazil 2008
Brazil 2009
Brazil 2010
Brazil 2011
Brazil 2012
Brazil 2013
Brazil 2014
Brazil 2015
Brazil : 697.555187721124
British Virgin Islands 1998
British Virgin Islands 1999
British Virgin Islands : 392.6842105263158
Burkina Faso 1998
Burkina Faso 1999
Burkina Faso 2000
Burkina Faso 2001
Burkina Faso 2002
Burkina Faso 2003
Burkina Faso 2004
Burkina Faso 2005
Burkina Faso 2006
Burkina Faso 2007
Burkina Faso 2008
Burkina Faso 2009
Burkina Faso 2010
Burkina Faso 2011
Burkina Faso 2012
Burkina Faso 2013
Burkina Faso 2014
Burkina Faso 2015
Burkina Faso : 1178.085107573239
Burundi 1998
Burundi 1999
Burundi 2000
Burundi 2001
Burundi 2002
Burundi 2003
Burundi 2004
Burundi 2005
Burundi 2006
Burundi 2007
Burundi 2008
Burundi 2009
Burundi 2010
Burundi 2011
Burundi 2012
Burundi 2013
Burundi 2014
Burundi 2015
Burundi : 921.7000568387037
CEEC, Total 1998
CEEC, Total 1999
CEEC, Total 2000
CEEC, Total 2001
CEEC, Total 2002
CEEC, Total 2003
CEEC, Total 2004
CEEC, Total 2005
CEEC, Total 2006
CEEC, Total 2007
CEEC, Total 2008
CEEC, Total 2009
CEEC, Total 2010
CEEC, Total 2011
CEEC, Total 2012
CEEC, Total 2013
CEEC, Total 2014
CEEC, Total 2015
CEEC, Total : 0
Cabo Verde 1998
Cabo Verde 1999
Cabo Verde 2000
Cabo Verde 2001
Cabo Verde 2002
Cabo Verde 2003
Cabo Verde 2004
Cabo Verde 2005
Cabo Verde 2006
Cabo Verde 2007
Cabo Verde 2008
Cabo Verde 2009
Cabo Verde 2010
Cabo Verde 2011
Cabo Verde 2012
Cabo Verde 2013
Cabo Verde 2014
Cabo Verde 2015
Cabo Verde : 9062.647536307431
Cambodia 1998
Cambodia 1999
Cambodia 2000
Cambodia 2001
Cambodia 2002
Cambodia 2003
Cambodia 2004
Cambodia 2005
Cambodia 2006
Cambodia 2007
Cambodia 2008
Cambodia 2009
Cambodia 2010
Cambodia 2011
Cambodia 2012
Cambodia 2013
Cambodia 2014
Cambodia 2015
Cambodia : 859.9326313772968
Cameroon 1998
Cameroon 1999
Cameroon 2000
Cameroon 2001
Cameroon 2002
Cameroon 2003
Cameroon 2004
Cameroon 2005
Cameroon 2006
Cameroon 2007
Cameroon 2008
Cameroon 2009
Cameroon 2010
Cameroon 2011
Cameroon 2012
Cameroon 2013
Cameroon 2014
Cameroon 2015
Cameroon : 1167.9182113473958
Central African Republic 1998
Central African Republic 1999
Central African Republic 2000
Central African Republic 2001
Central African Republic 2002
Central African Republic 2003
Central African Republic 2004
Central African Republic 2005
Central African Republic 2006
Central African Republic 2007
Central African Republic 2008
Central African Republic 2009
Central African Republic 2010
Central African Republic 2011
Central African Republic 2012
Central African Republic 2013
Central African Republic 2014
Central African Republic 2015
Central African Republic : 989.2078759134126
Central Asia, regional 1999
Central Asia, regional 2000
Central Asia, regional 2001
Central Asia, regional 2002
Central Asia, regional 2003
Central Asia, regional 2004
Central Asia, regional 2005
Central Asia, regional 2006
Central Asia, regional 2007
Central Asia, regional 2008
Central Asia, regional 2009
Central Asia, regional 2010
Central Asia, regional 2011
Central Asia, regional 2012
Central Asia, regional 2013
Central Asia, regional 2014
Central Asia, regional 2015
Central Asia, regional : 0
Chad 1998
Chad 1999
Chad 2000
Chad 2001
Chad 2002
Chad 2003
Chad 2004
Chad 2005
Chad 2006
Chad 2007
Chad 2008
Chad 2009
Chad 2010
Chad 2011
Chad 2012
Chad 2013
Chad 2014
Chad 2015
Chad : 744.7768666759187
Chile 1998
Chile 1999
Chile 2000
Chile 2001
Chile 2002
Chile 2003
Chile 2004
Chile 2005
Chile 2006
Chile 2007
Chile 2008
Chile 2009
Chile 2010
Chile 2011
Chile 2012
Chile 2013
Chile 2014
Chile 2015
Chile : 1536.4005552989167
China (People's Republic of) 1998
China (People's Republic of) 1999
China (People's Republic of) 2000
China (People's Republic of) 2001
China (People's Republic of) 2002
China (People's Republic of) 2003
China (People's Republic of) 2004
China (People's Republic of) 2005
China (People's Republic of) 2006
China (People's Republic of) 2007
China (People's Republic of) 2008
China (People's Republic of) 2009
China (People's Republic of) 2010
China (People's Republic of) 2011
China (People's Republic of) 2012
China (People's Republic of) 2013
China (People's Republic of) 2014
China (People's Republic of) 2015
China (People's Republic of) : 0
Club du Sahel, Total 1998
Club du Sahel, Total 1999
Club du Sahel, Total 2000
Club du Sahel, Total 2001
Club du Sahel, Total 2002
Club du Sahel, Total 2003
Club du Sahel, Total 2004
Club du Sahel, Total 2005
Club du Sahel, Total 2006
Club du Sahel, Total 2007
Club du Sahel, Total 2008
Club du Sahel, Total 2009
Club du Sahel, Total 2010
Club du Sahel, Total 2011
Club du Sahel, Total 2012
Club du Sahel, Total 2013
Club du Sahel, Total 2014
Club du Sahel, Total 2015
Club du Sahel, Total : 0
Colombia 1998
Colombia 1999
Colombia 2000
Colombia 2001
Colombia 2002
Colombia 2003
Colombia 2004
Colombia 2005
Colombia 2006
Colombia 2007
Colombia 2008
Colombia 2009
Colombia 2010
Colombia 2011
Colombia 2012
Colombia 2013
Colombia 2014
Colombia 2015
Colombia : 1121.310553490965
Comoros 1998
Comoros 1999
Comoros 2000
Comoros 2001
Comoros 2002
Comoros 2003
Comoros 2004
Comoros 2005
Comoros 2006
Comoros 2007
Comoros 2008
Comoros 2009
Comoros 2010
Comoros 2011
Comoros 2012
Comoros 2013
Comoros 2014
Comoros 2015
Comoros : 1594.7228440926924
Congo 1998
Congo 1999
Congo 2000
Congo 2001
Congo 2002
Congo 2003
Congo 2004
Congo 2005
Congo 2006
Congo 2007
Congo 2008
Congo 2009
Congo 2010
Congo 2011
Congo 2012
Congo 2013
Congo 2014
Congo 2015
Congo : 1979.0304243731819
Cook Islands 1998
Cook Islands 1999
Cook Islands 2000
Cook Islands 2001
Cook Islands 2002
Cook Islands 2003
Cook Islands 2004
Cook Islands 2005
Cook Islands 2006
Cook Islands 2007
Cook Islands 2008
Cook Islands 2009
Cook Islands 2010
Cook Islands 2011
Cook Islands 2012
Cook Islands 2013
Cook Islands 2014
Cook Islands 2015
Cook Islands : 15688.96955624355
Costa Rica 1998
Costa Rica 1999
Costa Rica 2000
Costa Rica 2001
Costa Rica 2002
Costa Rica 2003
Costa Rica 2004
Costa Rica 2005
Costa Rica 2006
Costa Rica 2007
Costa Rica 2008
Costa Rica 2009
Costa Rica 2010
Costa Rica 2011
Costa Rica 2012
Costa Rica 2013
Costa Rica 2014
Costa Rica 2015
Costa Rica : 1429.0695741653255
Croatia 1998
Croatia 1999
Croatia 2000
Croatia 2001
Croatia 2002
Croatia 2003
Croatia 2004
Croatia 2005
Croatia 2006
Croatia 2007
Croatia 2008
Croatia 2009
Croatia 2010
Croatia : 2493.5863858785588
Cuba 1998
Cuba 1999
Cuba 2000
Cuba 2001
Cuba 2002
Cuba 2003
Cuba 2004
Cuba 2005
Cuba 2006
Cuba 2007
Cuba 2008
Cuba 2009
Cuba 2010
Cuba 2011
Cuba 2012
Cuba 2013
Cuba 2014
Cuba 2015
Cuba : 250.84040639978724
CÃ´te d'Ivoire 1998
CÃ´te d'Ivoire 1999
CÃ´te d'Ivoire 2000
CÃ´te d'Ivoire 2001
CÃ´te d'Ivoire 2002
CÃ´te d'Ivoire 2003
CÃ´te d'Ivoire 2004
CÃ´te d'Ivoire 2005
CÃ´te d'Ivoire 2006
CÃ´te d'Ivoire 2007
CÃ´te d'Ivoire 2008
CÃ´te d'Ivoire 2009
CÃ´te d'Ivoire 2010
CÃ´te d'Ivoire 2011
CÃ´te d'Ivoire 2012
CÃ´te d'Ivoire 2013
CÃ´te d'Ivoire 2014
CÃ´te d'Ivoire 2015
CÃ´te d'Ivoire : 0
Democratic People's Republic of Korea 1998
Democratic People's Republic of Korea 1999
Democratic People's Republic of Korea 2000
Democratic People's Republic of Korea 2001
Democratic People's Republic of Korea 2002
Democratic People's Republic of Korea 2003
Democratic People's Republic of Korea 2004
Democratic People's Republic of Korea 2005
Democratic People's Republic of Korea 2006
Democratic People's Republic of Korea 2007
Democratic People's Republic of Korea 2008
Democratic People's Republic of Korea 2009
Democratic People's Republic of Korea 2010
Democratic People's Republic of Korea 2011
Democratic People's Republic of Korea 2012
Democratic People's Republic of Korea 2013
Democratic People's Republic of Korea 2014
Democratic People's Republic of Korea 2015
Democratic People's Republic of Korea : 0
Democratic Republic of the Congo 1998
Democratic Republic of the Congo 1999
Democratic Republic of the Congo 2000
Democratic Republic of the Congo 2001
Democratic Republic of the Congo 2002
Democratic Republic of the Congo 2003
Democratic Republic of the Congo 2004
Democratic Republic of the Congo 2005
Democratic Republic of the Congo 2006
Democratic Republic of the Congo 2007
Democratic Republic of the Congo 2008
Democratic Republic of the Congo 2009
Democratic Republic of the Congo 2010
Democratic Republic of the Congo 2011
Democratic Republic of the Congo 2012
Democratic Republic of the Congo 2013
Democratic Republic of the Congo 2014
Democratic Republic of the Congo 2015
Democratic Republic of the Congo : 780.2010835501289
Developing Countries, Total 1998
Developing Countries, Total 1999
Developing Countries, Total 2000
Developing Countries, Total 2001
Developing Countries, Total 2002
Developing Countries, Total 2003
Developing Countries, Total 2004
Developing Countries, Total 2005
Developing Countries, Total 2006
Developing Countries, Total 2007
Developing Countries, Total 2008
Developing Countries, Total 2009
Developing Countries, Total 2010
Developing Countries, Total 2011
Developing Countries, Total 2012
Developing Countries, Total 2013
Developing Countries, Total 2014
Developing Countries, Total 2015
Developing Countries, Total : 0
Developing countries, unspecified 1998
Developing countries, unspecified 1999
Developing countries, unspecified 2000
Developing countries, unspecified 2001
Developing countries, unspecified 2002
Developing countries, unspecified 2003
Developing countries, unspecified 2004
Developing countries, unspecified 2005
Developing countries, unspecified 2006
Developing countries, unspecified 2007
Developing countries, unspecified 2008
Developing countries, unspecified 2009
Developing countries, unspecified 2010
Developing countries, unspecified 2011
Developing countries, unspecified 2012
Developing countries, unspecified 2013
Developing countries, unspecified 2014
Developing countries, unspecified 2015
Developing countries, unspecified : 0
Djibouti 1998
Djibouti 1999
Djibouti 2000
Djibouti 2001
Djibouti 2002
Djibouti 2003
Djibouti 2004
Djibouti 2005
Djibouti 2006
Djibouti 2007
Djibouti 2008
Djibouti 2009
Djibouti 2010
Djibouti 2011
Djibouti 2012
Djibouti 2013
Djibouti 2014
Djibouti 2015
Djibouti : 3187.6776395307174
Dominica 1998
Dominica 1999
Dominica 2000
Dominica 2001
Dominica 2002
Dominica 2003
Dominica 2004
Dominica 2005
Dominica 2006
Dominica 2007
Dominica 2008
Dominica 2009
Dominica 2010
Dominica 2011
Dominica 2012
Dominica 2013
Dominica 2014
Dominica 2015
Dominica : 8578.37157725654
Dominican Republic 1998
Dominican Republic 1999
Dominican Republic 2000
Dominican Republic 2001
Dominican Republic 2002
Dominican Republic 2003
Dominican Republic 2004
Dominican Republic 2005
Dominican Republic 2006
Dominican Republic 2007
Dominican Republic 2008
Dominican Republic 2009
Dominican Republic 2010
Dominican Republic 2011
Dominican Republic 2012
Dominican Republic 2013
Dominican Republic 2014
Dominican Republic 2015
Dominican Republic : 1464.8121575496325
Ecuador 1998
Ecuador 1999
Ecuador 2000
Ecuador 2001
Ecuador 2002
Ecuador 2003
Ecuador 2004
Ecuador 2005
Ecuador 2006
Ecuador 2007
Ecuador 2008
Ecuador 2009
Ecuador 2010
Ecuador 2011
Ecuador 2012
Ecuador 2013
Ecuador 2014
Ecuador 2015
Ecuador : 881.9917907020275
Egypt 1998
Egypt 1999
Egypt 2000
Egypt 2001
Egypt 2002
Egypt 2003
Egypt 2004
Egypt 2005
Egypt 2006
Egypt 2007
Egypt 2008
Egypt 2009
Egypt 2010
Egypt 2011
Egypt 2012
Egypt 2013
Egypt 2014
Egypt 2015
Egypt : 939.9631227611203
El Salvador 1998
El Salvador 1999
El Salvador 2000
El Salvador 2001
El Salvador 2002
El Salvador 2003
El Salvador 2004
El Salvador 2005
El Salvador 2006
El Salvador 2007
El Salvador 2008
El Salvador 2009
El Salvador 2010
El Salvador 2011
El Salvador 2012
El Salvador 2013
El Salvador 2014

In [9]:
#sanity checks
print(emptyframe.head())

              Recipient  Average Sum of Money
0  ACP Countries, Total              0.000000
1           Afghanistan            118.393202
2         Africa, Total              0.000000
3      Africa, regional              0.000000
4               Albania            163.510014

In [10]:
#dropping all NaNs
print(len(emptyframe))
emptyframe=emptyframe.dropna(axis=1, how='any')
print(len(emptyframe))

210
210

In [11]:
#saving the list of all recipients
emptyframe.to_csv("Raw_Data/AllRecipientsPerCap.csv", index=False)

In [12]:
#now we load the file of migration of the last 20 years in OECD countries
#so this is a statistic for each OECD country noting how many migrants from each country it has uptaken in each year
rawfilemig=pd.read_csv("/Users/halukamaier-borst/Desktop/DW_DevelopmentalAid/DW_Code/Raw_Data/Mig_RAW_20yrs.csv")

In [13]:
rawfilemig.head()

,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value,Flag Codes,Flags
0,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,1997,1997,368.0,NaN,NaN
1,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,1998,1998,620.0,NaN,NaN
2,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,1999,1999,852.0,NaN,NaN
3,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2000,2000,887.0,NaN,NaN
4,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2001,2001,456.0,NaN,NaN

In [14]:
#we first sort the dataframe by the country of birth, then the country they migrated to and then by the year
rawfilemig=rawfilemig.sort_values(by=['Country of birth/nationality', 'Country','Year'])

In [28]:
#we load this data in
testdata=rawfilemig
#testdata=testdata.head(1000)
testdata

,CO2,Country of birth/nationality,VAR,Variable,GEN,Gender,COU,Country,YEA,Year,Value,Flag Codes,Flags
0,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,1997,1997,368.0,NaN,NaN
1,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,1998,1998,620.0,NaN,NaN
2,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,1999,1999,852.0,NaN,NaN
3,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2000,2000,887.0,NaN,NaN
4,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2001,2001,456.0,NaN,NaN
5,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2002,2002,660.0,NaN,NaN
6,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2003,2003,1015.0,NaN,NaN
7,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2004,2004,1340.0,NaN,NaN
8,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2005,2005,3463.0,NaN,NaN
9,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2006,2006,3465.0,NaN,NaN
10,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2007,2007,2560.0,NaN,NaN
11,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2008,2008,2033.0,NaN,NaN
12,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2009,2009,1696.0,NaN,NaN
13,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2010,2010,1618.0,NaN,NaN
14,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2011,2011,2030.0,NaN,NaN
15,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2012,2012,1623.0,NaN,NaN
16,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2013,2013,2178.0,NaN,NaN
17,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2014,2014,5686.0,NaN,NaN
18,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUS,Australia,2015,2015,3323.0,NaN,NaN
19,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,1998,1998,198.0,NaN,NaN
20,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,1999,1999,553.0,NaN,NaN
21,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2000,2000,828.0,NaN,NaN
22,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2001,2001,1539.0,NaN,NaN
23,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2002,2002,1101.0,NaN,NaN
24,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2003,2003,743.0,NaN,NaN
25,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2004,2004,650.0,NaN,NaN
26,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2005,2005,652.0,NaN,NaN
27,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2006,2006,498.0,NaN,NaN
28,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2007,2007,530.0,NaN,NaN
29,AFG,Afghanistan,B11,Inflows of foreign population by nationality,TOT,Total,AUT,Austria,2008,2008,958.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
84747,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,TUR,Turkey,1997,1997,0.0,NaN,NaN
84748,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,TUR,Turkey,1998,1998,0.0,NaN,NaN
84749,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,TUR,Turkey,2010,2010,2.0,NaN,NaN
84750,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,GBR,United Kingdom,1996,1996,1000.0,NaN,NaN
84751,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,GBR,United Kingdom,1998,1998,1843.0,NaN,NaN
84752,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,GBR,United Kingdom,1999,1999,2728.0,NaN,NaN
84753,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,GBR,United Kingdom,2000,2000,2123.0,NaN,NaN
84754,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,GBR,United Kingdom,2001,2001,4400.0,NaN,NaN
84755,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,GBR,United Kingdom,2011,2011,1000.0,NaN,NaN
84756,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,GBR,United Kingdom,2012,2012,2000.0,NaN,NaN
84757,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,GBR,United Kingdom,2015,2015,1000.0,NaN,NaN
84758,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,1997,1997,274.0,NaN,NaN
84759,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,1998,1998,186.0,NaN,NaN
84760,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,1999,1999,184.0,NaN,NaN
84761,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2000,2000,322.0,NaN,NaN
84762,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2001,2001,475.0,NaN,NaN
84763,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2002,2002,484.0,NaN,NaN
84764,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2003,2003,358.0,NaN,NaN
84765,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2004,2004,628.0,NaN,NaN
84766,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2005,2005,923.0,NaN,NaN
84767,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2006,2006,1049.0,NaN,NaN
84768,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2007,2007,1057.0,NaN,NaN
84769,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2008,2008,953.0,NaN,NaN
84770,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2009,2009,983.0,NaN,NaN
84771,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2010,2010,1274.0,NaN,NaN
84772,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2011,2011,1016.0,NaN,NaN
84773,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2012,2012,914.0,NaN,NaN
84774,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2013,2013,924.0,NaN,NaN
84775,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2014,2014,797.0,NaN,NaN
84776,ZWE,Zimbabwe,B11,Inflows of foreign population by nationality,TOT,Total,USA,United States,2015,2015,779.0,NaN,NaN

In [29]:
#again we define an empty dataframe
emptyframe2 = pd.DataFrame(columns=['Country of Birth',"Destination",'Emigration'])
#set a couple of variables to default values
previousbirth="0"
previousdestination="0"
year=0
sum20=0
#and now we iterate through the dataframe
for index, row in testdata.iterrows():
    #only when the variable is about the inflow we process the data
    if row[3]=="Inflows of foreign population by nationality":
        #we set the birthcountry variable on the "Country of birth/nationality" value of the row
        birthcountry=row[1]
        annus=str(row["Year"])
        #we set the migdestination variable on the "Country" value of the row, so the country that has taken up the migrants
        migdestination=row["Country"]
        #whenever either the previousrow's country of birth or the destination is different, this if-statement is true
        if (previousbirth != "0" and previousbirth!=birthcountry) or (previousdestination != "0" and previousdestination!=migdestination) :
            #in cases we have a year value of zero, we have an average of zero
            if year==0:
                average=0
                #print(previousbirth,":",sum20)
            #otherwise the average is defined as the sum over the years divided by the number of years
            else:
                average=sum20/year
            #and then a new row is appended to the empty dataframe with the country of birth, 
            #the destination and the average number of migrants
            df2 = pd.DataFrame([[previousbirth, previousdestination,average]], columns=['Country of Birth',"Destination",'Emigration'])
            emptyframe2=emptyframe2.append(df2,ignore_index=True)
            #print(previousbirth,":",sum20)
            try:
                #the sum over the years is then resetted to one and the number of migrants from this row is added to the sum
                sum20=0
                migpercap=row["Value"]/(int(population.loc[birthcountry][annus].replace(" ", ""))*1000)

                sum20+=migpercap
                #the number of years is set to 0 and then to 1
                year=0
                year+=1
                # the previousbirth variable becomes the current birthcountry
                previousbirth=birthcountry
                # the previousdestination variable becomes the current destinationcounrty
                previousdestination=migdestination
            except KeyError:
                previousdestination=migdestination

        else:
            #if the previousbirthcountry is the same as the current one
            #as well as the previous migration destination and the current one
            #we add the number of migrants of the current row to the sum
            try:
                migpercap=row["Value"]/(int(population.loc[birthcountry][annus].replace(" ", ""))*1000)
                sum20+=migpercap
                #we add one year
                year+=1
                # the previousbirth variable becomes the current birthcountry
                previousbirth=birthcountry
                # the previousdestination variable becomes the current destinationcounrty
                previousdestination=migdestination
            except KeyError:
                previousdestination=migdestination

In [30]:
emptyframe2

      Country of Birth      Destination    Emigration
0          Afghanistan        Australia  6.913380e-05
1          Afghanistan          Austria  7.923389e-05
2          Afghanistan          Belgium  5.758812e-05
3          Afghanistan           Canada  1.011086e-04
4          Afghanistan            Chile  1.010187e-07
5          Afghanistan   Czech Republic  1.462716e-06
6          Afghanistan          Denmark  2.772384e-05
7          Afghanistan          Estonia  2.083512e-08
8          Afghanistan          Finland  1.084316e-05
9          Afghanistan           France  1.057102e-05
10         Afghanistan          Germany  3.349763e-04
11         Afghanistan          Hungary  8.332016e-07
12         Afghanistan          Iceland  4.525228e-08
13         Afghanistan           Israel  0.000000e+00
14         Afghanistan            Italy  2.373539e-05
15         Afghanistan            Japan  1.995150e-05
16         Afghanistan            Korea  2.275359e-06
17         Afghanistan           Latvia  2.964193e-08
18         Afghanistan       Luxembourg  4.901531e-07
19         Afghanistan           Mexico  4.528951e-08
20         Afghanistan      Netherlands  1.723081e-05
21         Afghanistan      New Zealand  8.538615e-06
22         Afghanistan           Norway  3.001723e-05
23         Afghanistan           Poland  1.313587e-06
24         Afghanistan  Slovak Republic  8.634539e-07
25         Afghanistan         Slovenia  6.016882e-08
26         Afghanistan            Spain  1.486240e-06
27         Afghanistan           Sweden  6.120134e-05
28         Afghanistan      Switzerland  1.052259e-05
29         Afghanistan           Turkey  1.384424e-04
...                ...              ...           ...
16416         Zimbabwe        Australia  7.116980e-05
16417         Zimbabwe          Austria  1.222675e-06
16418         Zimbabwe          Belgium  2.114930e-06
16419         Zimbabwe           Canada  2.939923e-05
16420         Zimbabwe            Chile  4.130110e-08
16421         Zimbabwe   Czech Republic  3.237269e-07
16422         Zimbabwe          Denmark  9.108441e-07
16423         Zimbabwe          Estonia  0.000000e+00
16424         Zimbabwe          Finland  2.395268e-07
16425         Zimbabwe           France  8.241910e-07
16426         Zimbabwe          Germany  1.032370e-05
16427         Zimbabwe          Hungary  1.154175e-07
16428         Zimbabwe          Iceland  1.202731e-08
16429         Zimbabwe            Italy  1.378546e-06
16430         Zimbabwe            Japan  7.955154e-06
16431         Zimbabwe            Korea  8.715605e-07
16432         Zimbabwe           Latvia  0.000000e+00
16433         Zimbabwe       Luxembourg  8.076692e-08
16434         Zimbabwe           Mexico  2.154939e-07
16435         Zimbabwe      Netherlands  6.788323e-06
16436         Zimbabwe      New Zealand  1.894680e-05
16437         Zimbabwe           Norway  1.428235e-06
16438         Zimbabwe           Poland  1.755701e-06
16439         Zimbabwe  Slovak Republic  7.281194e-08
16440         Zimbabwe         Slovenia  6.948441e-08
16441         Zimbabwe            Spain  7.772816e-07
16442         Zimbabwe           Sweden  1.627208e-06
16443         Zimbabwe      Switzerland  2.615473e-06
16444         Zimbabwe           Turkey  3.549624e-08
16445         Zimbabwe   United Kingdom  1.582819e-04

[16446 rows x 3 columns]

In [31]:
#and then we save this dataframe that consists of all bilateral migrations as an average over the years
emptyframe2.to_csv("/Users/halukamaier-borst/Desktop/DW_DevelopmentalAid/DW_Code/Raw_Data/AllMig_bilateralPerCap.csv",index=False)

In [32]:
#now we use this newly created dataframe to calculate the overall outflow of migrants from any country into OECD countries
testdata=emptyframe2
emptyframe2.head()

  Country of Birth Destination    Emigration
0      Afghanistan   Australia  6.913380e-05
1      Afghanistan     Austria  7.923389e-05
2      Afghanistan     Belgium  5.758812e-05
3      Afghanistan      Canada  1.011086e-04
4      Afghanistan       Chile  1.010187e-07

In [33]:
#again we create an emptydataframe
emptyframe3 = pd.DataFrame(columns=['Country of Birth','Average of emigration over all OECD countries'])
#we set the variables to default values
previousbirth="0"
sumOECD=0
#we iterate through the dataframe
for index, row in testdata.iterrows():
    #in each row the birthcountry variable is taken from the rows 0th column
    birthcountry=row[0]
    #if the previousbirth country was not the default value and is not the current birth country...
    if (previousbirth != "0" and previousbirth!=birthcountry):
        #we then append the country of birth and the sum of emigration to the dataframe
        df2 = pd.DataFrame([[previousbirth,sumOECD]], columns=['Country of Birth','Average of emigration over all OECD countries'])
        emptyframe3=emptyframe3.append(df2,ignore_index=True)
        print(previousbirth,":",sumOECD)
        #we reset the number of migrants to zero and then add the value of the current row
        sumOECD=0
        sumOECD+=row["Emigration"]
        #and we change the previousbirth variable to the one of the current country
        previousbirth=birthcountry
    #if the previous row and the current row have the same birthcountry then...
    else:
        #we add the value of emigration to the sum
        sumOECD=row["Emigration"]
        #and we change the previousbirth variable to the one of the current country
        previousbirth=birthcountry

Afghanistan : 9.999928944426401e-05
Albania : 0.001498124548141241
Algeria : 3.2421318958025736e-05
Andorra : 0.0
Angola : 6.554843665625282e-06
Antigua and Barbuda : 0.0044177757870465
Argentina : 0.00010341780983188897
Armenia : 0.0008910636519557732
Australia : 0.00011460565992599263
Austria : 5.203065632329292e-05
Azerbaijan : 0.00011570437575650382
Bahamas : 0.002024603710703897
Bahrain : 0.00011356395184182199
Bangladesh : 7.485125108034589e-05
Barbados : 0.002331895237639932
Belarus : 0.00023323229183465496
Belgium : 5.913006078053569e-05
Belize : 0.002975392718934955
Benin : 2.8337273448157638e-05
Bermuda : 0.0014687749214330286
Bhutan : 0.0
Bosnia and Herzegovina : 0.0016854967323352808
Botswana : 2.1671184607128425e-05
Brazil : 5.523295970036163e-05
Brunei Darussalam : 6.582985287575641e-05
Bulgaria : 0.0004579191865295056
Burkina Faso : 1.5868219946168576e-05
Burundi : 3.656268174820769e-05
Cambodia : 0.00020879695730077448
Cameroon : 0.00012875834221199212
Canada : 0.0
Central African Republic : 1.6029549833236363e-05
Chad : 6.476955885087033e-06
Chile : 0.00011116836795637934
China : 0.0
Colombia : 0.0004741192623079757
Comoros : 8.155369112972608e-06
Congo : 0.00023940514141723495
Cook Islands : 0.0001387719298245614
Costa Rica : 0.0004362999794441612
Croatia : 0.00022082855509596483
Cuba : 0.0027970210348872656
Cyprus : 0.0
Democratic Republic of the Congo : 2.1425242289679746e-05
Denmark : 9.796522204028766e-05
Djibouti : 7.36734980508173e-05
Dominica : 0.003974334430842041
Dominican Republic : 0.0035852106144281513
Ecuador : 0.0007337382627765211
Egypt : 9.317490308381574e-05
El Salvador : 0.00359126586996334
Equatorial Guinea : 1.234904846129769e-05
Eritrea : 0.0003004296550516166
Estonia : 0.00019929561170568157
Ethiopia : 0.0001243623296003579
Fiji : 0.001578135336865091
Finland : 0.0
France : 6.090215719530568e-05
Gabon : 5.5924579210495256e-05
Gambia : 0.0004088893159568391
Georgia : 0.0002649259758412399
Germany : 8.433537317175675e-05
Ghana : 0.0002927513935352017
Greece : 8.573747264278646e-05
Grenada : 0.0066399042651272
Guam : 0.0
Guatemala : 0.0009685111117492011
Guinea : 7.626377236080984e-05
Guinea-Bissau : 6.40461473066651e-05
Guyana : 0.009018164583394135
Haiti : 0.002129076440914017
Honduras : 0.0
Hungary : 0.00011289690238331168
Iceland : 0.000371909348974469
India : 5.179473590174725e-05
Indonesia : 0.0
Iraq : 0.00029365897418164364
Ireland : 0.0003414778529007553
Israel : 0.0005777154884906344
Italy : 4.398844081762927e-05
Jamaica : 0.006556120241002504
Japan : 5.1790827793990795e-05
Jordan : 0.0006517028641852574
Kazakhstan : 9.476178073761155e-05
Kenya : 0.00013374400031741164
Kiribati : 0.0
Kuwait : 0.00040623672642226417
Kyrgyzstan : 0.0
Latvia : 0.00023951760193466
Lebanon : 0.0009381924365030545
Lesotho : 6.725292402571146e-06
Liberia : 0.0010600905680885101
Libya : 4.710204243912634e-05
Liechtenstein : 8.412698412698413e-05
Lithuania : 0.00040797879692600677
Luxembourg : 0.0
Madagascar : 3.1367651150394124e-06
Malawi : 7.916238557802236e-06
Malaysia : 7.514499048790887e-05
Maldives : 1.5878761536560543e-05
Mali : 2.4599992775255826e-05
Malta : 0.00013560904401900887
Marshall Islands : 0.0005969750210067986
Mauritania : 9.43930511540497e-05
Mauritius : 6.314656377932118e-05
Mexico : 0.001454299115845636
Micronesia : 0.0
Monaco : 0.0002082153411186195
Mongolia : 0.00014919100317833302
Montenegro : 0.00037075841923156944
Morocco : 0.0001260089933804933
Mozambique : 2.7599275324503716e-06
Myanmar : 0.00014432343923571317
Namibia : 2.2312336735991615e-05
Nauru : 0.00024727272727272727
Nepal : 0.0001836905986989606
Netherlands : 7.81059362320764e-05
New Zealand : 0.00022105244368495513
Nicaragua : 0.0012252002846411315
Niger : 2.436919596937671e-05
Nigeria : 7.362990807287283e-05
Niue : 0.0
Norway : 0.0
Oman : 2.6967289357448556e-05
Pakistan : 9.732947671898069e-05
Palau : 0.0
Panama : 0.00048095821709702143
Papua New Guinea : 3.5347758326746927e-06
Paraguay : 7.034558974513384e-05
Peru : 0.0004626619389431397
Philippines : 0.0006207112499136942
Poland : 0.0002635554862629338
Portugal : 0.00011351907073072814
Puerto Rico : 0.0
Qatar : 0.0001276177211389497
Romania : 0.0
Rwanda : 3.6821194091367644e-05
Saint Kitts and Nevis : 0.00693730150602001
Saint Lucia : 0.004579695046937083
Saint Vincent and the Grenadines : 0.004717769193626268
Samoa : 0.001120625727810416
San Marino : 0.0
Sao Tome and Principe : 4.6030628772605595e-05
Saudi Arabia : 4.7301910114736694e-05
Senegal : 7.93486097183324e-05
Serbia : 0.0
Seychelles : 0.0001480163749446669
Sierra Leone : 0.00034325662104585565
Singapore : 0.0
Slovenia : 4.347646759730702e-05
Solomon Islands : 1.2512571171447087e-05
Somalia : 0.0004789158170660224
South Africa : 5.86815447478591e-05
Spain : 3.8566711921669765e-05
Sri Lanka : 0.0
Sudan : 8.60611799654989e-05
Suriname : 0.00040824972743873687
Swaziland : 1.4959894260809345e-05
Sweden : 0.00012357369121061577
Switzerland : 0.0
Tajikistan : 0.0
Thailand : 9.524422785889206e-05
Timor-Leste : 2.4174053182917003e-06
Togo : 0.00019917275614873733
Tokelau : 0.0
Tonga : 0.0
Trinidad and Tobago : 0.004288071385734481
Tunisia : 3.834490197220491e-05
Turkey : 5.537164219242346e-05
Turkmenistan : 3.452196623538802e-05
Tuvalu : 0.0003
Uganda : 2.9253171724359944e-05
Ukraine : 0.00027280885007563904
United Arab Emirates : 0.00012109627068348049
United Kingdom : 0.0
Uruguay : 0.0002990818051421464
Uzbekistan : 0.00012538360477254312
Vanuatu : 0.0
Viet Nam : 0.0003562256731848511
Yemen : 0.00011556372073324195
Zambia : 3.460534074649321e-05

In [39]:
#now we rename this new dataframe and rename the column to prepare a merge
mig=emptyframe3.rename(index=str, columns={"Country of Birth": "Recipient"})
#and save the migration figures
mig.to_csv("migToOECD_avg.csv")
print(len(mig))
mig.head()

181

     Recipient  Average of emigration over all OECD countries
0  Afghanistan                                       0.000100
1      Albania                                       0.001498
2      Algeria                                       0.000032
3      Andorra                                       0.000000
4       Angola                                       0.000007

In [35]:
#we merge both dataframe by the column "Recipient" and only values are preserved that exist in both dataframes
result=pd.merge(emptyframe,mig, on="Recipient", how="inner")

In [36]:
#we get rid of all zero values and all NaN
result=result[(result != 0).all(1)]
result=result.dropna()
len(result)

122

In [37]:
#we check that each country only exists once in the dataframe
resultscount=result.groupby(['Recipient']).size().reset_index(name='count')
resultscount=resultscount.sort_values(by="count")
resultscount

                            Recipient  count
0                         Afghanistan      1
88                               Peru      1
87                           Paraguay      1
86                   Papua New Guinea      1
85                             Panama      1
84                           Pakistan      1
83                               Oman      1
82                            Nigeria      1
81                              Niger      1
80                          Nicaragua      1
79                              Nepal      1
78                              Nauru      1
77                            Namibia      1
89                        Philippines      1
76                            Myanmar      1
74                            Morocco      1
73                         Montenegro      1
72                           Mongolia      1
71                             Mexico      1
70                          Mauritius      1
69                         Mauritania      1
68                   Marshall Islands      1
67                              Malta      1
66                               Mali      1
65                           Maldives      1
64                           Malaysia      1
63                             Malawi      1
75                         Mozambique      1
90                             Rwanda      1
91              Saint Kitts and Nevis      1
..                                ...    ...
31   Democratic Republic of the Congo      1
58                            Lebanon      1
57                              Kenya      1
56                         Kazakhstan      1
55                             Jordan      1
54                            Jamaica      1
53                               Iraq      1
52                              India      1
51                              Haiti      1
50                             Guyana      1
49                      Guinea-Bissau      1
48                             Guinea      1
47                          Guatemala      1
46                            Grenada      1
45                              Ghana      1
44                            Georgia      1
43                             Gambia      1
42                              Gabon      1
41                               Fiji      1
40                           Ethiopia      1
39                            Eritrea      1
38                  Equatorial Guinea      1
37                        El Salvador      1
36                              Egypt      1
35                            Ecuador      1
34                 Dominican Republic      1
33                           Dominica      1
32                           Djibouti      1
30                               Cuba      1
121                            Zambia      1

[122 rows x 2 columns]

In [38]:
#and lastly save the results
result.to_csv("Raw_data/MigrationVSMoneyPerCap.csv", index=False)